# Generated by Django 4.1.2 on 2022-10-29 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(name="Contacts",),
    ]
