# Generated by Django 4.1.2 on 2022-10-29 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="aboutus", options={"verbose_name_plural": "About us"},
        ),
        migrations.AlterModelOptions(
            name="blogs", options={"verbose_name_plural": "Blogs"},
        ),
        migrations.AlterModelOptions(
            name="contacts", options={"verbose_name_plural": "Contacts"},
        ),
        migrations.AlterModelOptions(
            name="photos", options={"verbose_name_plural": "Photos"},
        ),
        migrations.RenameField(
            model_name="contacts", old_name="name", new_name="Name",
        ),
    ]
