# Generated by Django 4.1.2 on 2022-10-29 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_alter_aboutus_options_alter_blogs_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contacts", name="Email", field=models.EmailField(max_length=50),
        ),
    ]
